ock.mmc.meta_service_url = tcp://127.0.0.1:5000
ock.mmc.local_service.config_store_url = tcp://127.0.0.1:6000
ock.mmc.log_level = info
ock.mmc.local_service.world_size = 4
ock.mmc.local_service.protocol = host_shm
ock.mmc.local_service.dram.size = 1GB
